"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowUpRight, ChevronDown, Github, Linkedin, Mail, Menu, X, Terminal, ShieldCheck, Database, Server, Code2, Cloud, Download } from "lucide-react";

const skills=[
["IT Support", "Windows · Linux · Microsoft 365 · User support · Application support", Server],
["Backend", "Python · Java · Django · REST APIs · Authentication · Authorization", Code2],
["Databases", "SQL · MySQL · Database administration · Query troubleshooting · Data integrity", Database],
["Infrastructure", "Servers · Networking fundamentals · Application deployment · Cloud principles", Cloud],
["Security", "Access control · Secure coding · Identity & permissions · Cybersecurity concepts", ShieldCheck],
["Tools", "Git · GitHub · APIs · Development workflows · Technical documentation", Terminal]
];

const projects=[
["01","Backend / APIs","Business Web Applications","Backend modules, REST API integrations, application data and process automation for internal business workflows.",["Python","Django","REST","SQL"]],
["02","Product Concept","Tabby Home + Nanny","A product concept exploring on-demand home services and nanny booking with a technology-first user experience.",["Product","UX","Prototype"]],
["03","Security","Application Security","Exploring authentication, authorization, access control, permissions and secure backend practices.",["Security","RBAC","APIs"]],
["04","Database","Database & Application Support","SQL troubleshooting, application connectivity, data integrity and database-backed business applications.",["MySQL","SQL","Support"]]
];

export default function Home(){
 const [open,setOpen]=useState(false);
 const links=["About","Experience","Skills","Projects","Contact"];
 return <main className="min-h-screen overflow-hidden bg-[#070809] text-[#f4f5f6]">
  <div className="pointer-events-none fixed inset-0 -z-0 grid-bg opacity-70"/>
  <header className="fixed left-0 right-0 top-0 z-50 border-b border-white/10 bg-[#070809]/75 backdrop-blur-xl">
   <nav className="mx-auto flex h-[72px] max-w-6xl items-center justify-between px-5">
    <a href="#home" onClick={()=>setOpen(false)} className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center border border-[#b9ff3f] text-xs font-black text-[#b9ff3f]">MMT</span><span className="hidden text-sm font-semibold sm:block">Mir Mohammed Talha</span></a>
    <div className="hidden items-center gap-7 text-xs uppercase tracking-[.16em] text-white/55 md:flex">{links.map(x=><a key={x} href={"#"+x.toLowerCase()} className="hover:text-white">{x}</a>)}</div>
    <button onClick={()=>setOpen(!open)} className="grid h-10 w-10 place-items-center border border-white/10 md:hidden">{open?<X size={18}/>:<Menu size={18}/>}</button>
   </nav>
   {open&&<div className="border-t border-white/10 bg-[#070809] px-5 py-5 md:hidden">{links.map(x=><a key={x} href={"#"+x.toLowerCase()} onClick={()=>setOpen(false)} className="block border-b border-white/5 py-4 text-sm uppercase tracking-[.15em] text-white/65">{x}</a>)}</div>}
  </header>

  <section id="home" className="relative mx-auto grid min-h-screen max-w-6xl items-center gap-12 px-5 pb-20 pt-32 lg:grid-cols-[1.08fr_.92fr]">
   <motion.div initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.8}}>
    <p className="mb-6 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-white/45"><span className="h-2 w-2 rounded-full bg-[#b9ff3f] shadow-[0_0_18px_#b9ff3f]"/>IT · Backend · Cybersecurity</p>
    <h1 className="max-w-4xl text-[clamp(3.5rem,8vw,6.9rem)] font-black leading-[.88] tracking-[-.07em]">Technology that <span className="text-[#b9ff3f]">works.</span><br/>Systems that <span className="text-[#b9ff3f]">scale.</span></h1>
    <p className="mt-8 max-w-2xl text-base leading-7 text-white/50 sm:text-lg">I&apos;m Mir Mohammed Talha, an IT Support Specialist focused on reliable infrastructure, backend applications, APIs, databases and secure technology operations.</p>
    <div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#projects" className="inline-flex items-center justify-center gap-5 bg-[#b9ff3f] px-5 py-4 text-xs font-black uppercase tracking-[.12em] text-black hover:-translate-y-1">Explore my work <ArrowUpRight size={16}/></a><a href="#contact" className="inline-flex items-center justify-center border border-white/10 px-5 py-4 text-xs font-black uppercase tracking-[.12em] text-white/75 hover:border-[#b9ff3f] hover:text-[#b9ff3f]">Let&apos;s connect</a></div>
    <div className="mt-14 flex flex-wrap gap-x-8 gap-y-5">{[["IT Support","Infrastructure & users"],["Backend","APIs & databases"],["Security","Secure operations"]].map(x=><div key={x[0]}><p className="text-xs font-bold">{x[0]}</p><p className="mt-1 text-[11px] text-white/35">{x[1]}</p></div>)}</div>
   </motion.div>
   <motion.div initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} transition={{duration:1,delay:.15}} className="relative flex min-h-[440px] items-center justify-center">
    <div className="absolute h-72 w-72 rounded-full border border-[#b9ff3f]/20 shadow-[0_0_100px_rgba(185,255,63,.05)] sm:h-80 sm:w-80"/>
    <div className="absolute h-[380px] w-[380px] rounded-full border border-dashed border-[#b9ff3f]/10 [transform:rotate(22deg)] sm:h-[470px] sm:w-[470px]"/>
    <div className="relative grid h-56 w-56 place-items-center rounded-full border border-[#b9ff3f]/30 bg-[#0b0d0e] shadow-[0_0_80px_rgba(185,255,63,.07)] sm:h-64 sm:w-64"><span className="text-5xl font-black tracking-[-.08em] text-[#b9ff3f] sm:text-6xl">MMT</span></div>
    <div className="absolute bottom-0 right-0 w-[min(340px,90%)] border border-white/10 bg-[#0e1013]/95 shadow-2xl"><div className="flex h-9 items-center gap-1.5 border-b border-white/10 px-3"><i className="h-1.5 w-1.5 rounded-full bg-white/20"/><i className="h-1.5 w-1.5 rounded-full bg-white/20"/><i className="h-1.5 w-1.5 rounded-full bg-white/20"/><span className="ml-auto font-mono text-[9px] text-white/25">mmt://portfolio</span></div><div className="space-y-2 p-5 font-mono text-[11px] leading-5"><p><span className="text-white/25">$</span> whoami</p><p className="text-[#b9ff3f]">mir_mohammed_talha</p><p><span className="text-white/25">$</span> focus</p><p className="text-white/60">IT Support · Backend · Cybersecurity</p><p><span className="text-white/25">$</span> location</p><p className="text-white/60">Riyadh, Saudi Arabia</p><p><span className="text-white/25">$</span> status</p><p className="text-[#b9ff3f]">● available to connect</p></div></div>
   </motion.div>
   <a href="#about" className="absolute bottom-7 left-1/2 hidden -translate-x-1/2 items-center gap-2 text-[9px] uppercase tracking-[.25em] text-white/25 md:flex">Scroll to explore <ChevronDown size={13}/></a>
  </section>

  <div className="border-y border-white/10 py-4"><div className="mx-auto flex max-w-6xl flex-wrap justify-center gap-x-6 gap-y-2 px-5 text-[10px] font-bold uppercase tracking-[.16em] text-white/30 sm:justify-between">{["Python","Java","SQL","Django","REST APIs","Linux","Windows","Microsoft 365","Git","Cybersecurity"].map(x=><span key={x}>{x}</span>)}</div></div>

  <section id="about" className="mx-auto max-w-6xl px-5 py-28 sm:py-36"><p className="mb-12 font-mono text-[10px] font-bold uppercase tracking-[.16em] text-[#b9ff3f]">01 / About</p><div className="grid gap-12 lg:grid-cols-2 lg:gap-24"><h2 className="text-4xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl">More than support.<br/><span className="text-white/35">I build and improve systems.</span></h2><div className="space-y-5 text-sm leading-7 text-white/45 sm:text-base"><p>My work sits at the intersection of IT operations, application support and backend development. I troubleshoot business-critical issues, work with databases and APIs, support Windows/Linux environments, and help turn business requirements into practical technical solutions.</p><p>I&apos;m particularly interested in secure application design, automation, cloud technologies, cybersecurity and building technology that makes day-to-day operations more efficient.</p></div></div></section>

  <section id="experience" className="border-y border-white/10 bg-[#0e1013]"><div className="mx-auto max-w-6xl px-5 py-28 sm:py-36"><p className="mb-12 font-mono text-[10px] font-bold uppercase tracking-[.16em] text-[#b9ff3f]">02 / Experience</p><div className="grid gap-10 lg:grid-cols-2 lg:gap-24"><h2 className="text-4xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl">Professional<br/><span className="text-white/35">experience.</span></h2><p className="max-w-md self-end text-sm leading-7 text-white/40">Supporting people, applications and infrastructure while continuously improving the systems behind the work.</p></div><div className="mt-16 grid gap-8 border-t border-white/10 pt-8 md:grid-cols-[180px_1fr] md:gap-14"><p className="font-mono text-[10px] font-bold tracking-[.1em] text-[#b9ff3f]">JUN 2026 — PRESENT</p><div><h3 className="text-2xl font-bold sm:text-3xl">IT Support Specialist</h3><p className="mt-1 text-sm text-white/35">DesignTech Engineering Consultants · Riyadh, Saudi Arabia</p><ul className="mt-8 space-y-4 text-sm leading-6 text-white/50">{["Troubleshoot backend connectivity, database access and server-related issues for business-critical applications.","Support internal web applications and business-process automation initiatives.","Develop backend modules and integrate frontend applications with REST APIs.","Install, configure, test and maintain applications across Linux and Windows environments.","Manage application data, troubleshoot SQL queries and help maintain data integrity.","Support application access, Microsoft 365 accounts, permissions and day-to-day IT operations."].map(x=><li key={x} className="relative pl-5 before:absolute before:left-0 before:top-3 before:h-px before:w-1.5 before:bg-[#b9ff3f]">{x}</li>)}</ul></div></div></div></section>

  <section id="skills" className="mx-auto max-w-6xl px-5 py-28 sm:py-36"><p className="mb-12 font-mono text-[10px] font-bold uppercase tracking-[.16em] text-[#b9ff3f]">03 / Skills</p><div className="grid items-end gap-8 lg:grid-cols-2 lg:gap-24"><h2 className="text-4xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl">A practical<br/><span className="text-white/35">technical stack.</span></h2><p className="max-w-md text-sm leading-7 text-white/40">Tools and areas I work with across support, development, infrastructure and security.</p></div><div className="mt-16 grid border-l border-t border-white/10 sm:grid-cols-2 lg:grid-cols-3">{skills.map(([title,text,Icon],i)=>{const I=Icon as any;return <motion.article key={title as string} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.05}} className="group min-h-56 border-b border-r border-white/10 p-7 hover:bg-[#0e1013]"><div className="flex justify-between"><span className="font-mono text-[9px] text-[#b9ff3f]">0{i+1}</span><I size={20} className="text-white/25 group-hover:text-[#b9ff3f]"/></div><h3 className="mt-12 text-xl font-bold">{title as string}</h3><p className="mt-2 text-xs leading-6 text-white/35">{text as string}</p></motion.article>})}</div></section>

  <section id="projects" className="border-y border-white/10 bg-[#0a0b0d]"><div className="mx-auto max-w-6xl px-5 py-28 sm:py-36"><p className="mb-12 font-mono text-[10px] font-bold uppercase tracking-[.16em] text-[#b9ff3f]">04 / Selected Work</p><div className="grid items-end gap-8 lg:grid-cols-2 lg:gap-24"><h2 className="text-4xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl">Things I&apos;ve<br/><span className="text-white/35">worked on.</span></h2><p className="max-w-md text-sm leading-7 text-white/40">A starting set of case-study cards. We&apos;ll replace these with your real repositories, screenshots and live demos.</p></div><div className="mt-16 grid gap-4 sm:grid-cols-2">{projects.map((p,i)=><motion.article key={p[2] as string} whileHover={{y:-5}} className={`group flex min-h-[360px] flex-col justify-between border border-white/10 p-7 hover:border-[#b9ff3f]/40 ${i===0?"bg-[#111617]":"bg-[#0e1013]"}`}><div className="flex justify-between font-mono text-[9px] uppercase tracking-[.1em] text-white/30"><span>{p[0] as string}</span><span>{p[1] as string}</span></div><div><h3 className="text-2xl font-bold sm:text-3xl">{p[2] as string}</h3><p className="mt-4 text-sm leading-6 text-white/40">{p[3] as string}</p></div><div className="flex flex-wrap gap-2">{(p[4] as string[]).map(t=><span key={t} className="border border-white/10 px-2.5 py-1 text-[9px] uppercase tracking-[.1em] text-white/40">{t}</span>)}</div></motion.article>)}</div></div></section>

  <section className="mx-auto max-w-6xl px-5 py-28 text-center sm:py-36"><p className="mb-5 text-[10px] font-bold uppercase tracking-[.2em] text-white/30">Have a project, role or idea?</p><h2 className="text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-7xl">Let&apos;s build something<br/><span className="text-white/35">useful.</span></h2><a href="#contact" className="mt-10 inline-flex items-center gap-4 bg-[#b9ff3f] px-6 py-4 text-xs font-black uppercase tracking-[.12em] text-black hover:-translate-y-1">Get in touch <ArrowUpRight size={16}/></a></section>

  <section id="contact" className="border-t border-white/10"><div className="mx-auto max-w-6xl px-5 py-28 sm:py-36"><p className="mb-12 font-mono text-[10px] font-bold uppercase tracking-[.16em] text-[#b9ff3f]">05 / Contact</p><div className="grid gap-12 lg:grid-cols-2 lg:gap-24"><div><h2 className="text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-7xl">Let&apos;s<br/><span className="text-white/35">connect.</span></h2><p className="mt-7 max-w-md text-sm leading-7 text-white/40">For opportunities, collaborations or technical conversations, reach out through any of the channels below.</p></div><div className="border-t border-white/10">{[["Email",Mail,"mailto:YOUR_EMAIL@example.com","YOUR_EMAIL@example.com"],["LinkedIn",Linkedin,"https://www.linkedin.com/in/YOUR-LINKEDIN/","LinkedIn"],["GitHub",Github,"https://github.com/YOUR-GITHUB","GitHub"],["CV",Download,"#","Download CV"]].map(([name,I,href,label])=>{const Icon=I as any;return <a key={name as string} href={href as string} target={(href as string).startsWith("http")?"_blank":undefined} rel="noreferrer" className="flex items-center justify-between gap-5 border-b border-white/10 py-6 group"><span className="flex items-center gap-3 text-white/35"><Icon size={16}/>{name as string}</span><strong className="text-right text-sm font-medium group-hover:text-[#b9ff3f]">{label as string} ↗</strong></a>})}</div></div></div></section>

  <footer className="border-t border-white/10 py-7"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-3 px-5 text-[10px] text-white/25 sm:flex-row"><span>MMT © {new Date().getFullYear()}</span><span>Next.js · TypeScript · Tailwind · Framer Motion</span><a href="#home" className="hover:text-white">Back to top ↑</a></div></footer>
 </main>
}